---
title: "Introduction"
editor: 
  markdown: 
    wrap: 72
---

# Population assessments

**Population viability analysis (PVA)** is a conservation tool used to
help managers assess extinction risk and guide policy decisions. PVA is
mathematical model that uses demographic and life history data to
predict the long-term trend of a population, and its sensitivity to
changes in life history parameters or environmental stochasticity. This
allows users to assess the long-term impact of current threats, such as
fisheries bycatch, or conservation actions, such as nesting beach
protections.

## Conceptual Framework

PVA combines two primary components:

1.  **Retrospective fitting:** Estimating historical trends and current
    nesting female abundance based on empirical data.
2.  **Future projections:** A simulation approach to evaluate
    projections against abundance thresholds (here: the probability of
    falling below either 50%, 25%, or 12.5% of the current population
    size).
    

## Methods Outline

This assessment was performed in a **Bayesian framework** with four main
components: nesting data imputation, nesting trend analysis, population
viability analysis, and incorporation of fishery take into the PVA (the
"take model" component). The Bayesian framework is a statistical method
for combining a prior probability (existing knowledge) with new data
(likelihood) to produce a revised posterior probability. Instead of
using just a single estimate for a PVA, it provides a posterior
distribution that quantifies the uncertainty of parameters.

### 1. Imputing monthly nest counts

Monthly nest count data from different nesting beaches were available
for these analyses. However, some months were missing from the
leatherback dataset. Therefore, the dataset represents observed nests,
but those counts do not fully capture the true number of nests, as not
all nests in the population were observed. To fill in the gaps, we used
a Bayesian hierarchical model to impute the missing monthly nest counts
and produce a time series of annual nest counts.

The imputation model was autoregressive with a lag of one month, and the
relationship between the numbers of nests in two months was modeled by a
Fourier series. This allows the model to capture the periodicity of
nesting, e.g. Jamursba-Medi has one single summer peak in nesting, and
Wemon has both summer and winter peaks.

### 2. Trend analysis (retrospective)

Population growth rates are estimated using a stochastic
density-independent exponential growth model applied to nest count data
(Boyd et al. 2017[^1], Holmes et al. (2007)[^2]. This model is common
for long-lived, slow-growing, late-maturing species such as sea turtles,
whose populations have been depleted to relatively low levels.

[^1]: Boyd, C., D. P. DeMaster, R. S. Waples, E. J. Ward, and B. L.
    Taylor. 2017. Consistent extinction risk assessment under the US
    Endangered Species Act. Conservation Letters 10:328-336.

[^2]: Holmes EE, Sabo JL, Viscido SV, Fagan WF. 2007. A statistical
    approach to quasi‐extinction forecasting. Ecology Letters.
    10(12):1182-1198.

By dividing nest counts by clutch frequency, we calculated a time series
of annual nesters. Summing annual nesters across one remigration
interval provides a snapshot of the total nesters in the population.

We solved for population growth rate by subtracting the natural log of
annual nesters in one year by the natural log of annual nesters in the
previous year. This estimated population growth rate would be better
interpreted as long-term annual trends, as we use nests as a proxy for
nesters but cannot assume that their trend applies to adult males, or
immature turtles of both sexes.

Following Boyd et al. (2017), we construct a Bayesian state-space model
(BSSM) from the natural log version of the exponential population growth
equation. The BSSM allows for estimation of environmental and
demographic variability and imperfect data collection and provides
posterior distributions, which are useful for conveying uncertainty in
management applications.

There are two major components of the BSSM: the process model describing
the true number of nesting females each year, and the observation model
relating the observed count data to the true number of nesting females.
Three parameters are estimated: $r$, the instantaneous population growth
rate, $Q$, the process error variance, and $R$, the observation error
variance. The model also provides a predicted count with a probability
distribution for each year of observed data. The predicted value for the
final year of observed data is then used as a starting point for future
projections.

We define the model to only have one population with multiple time
series of observations (i.e., multiple beaches).This structure best
represents the known population dynamics of genetic similarity and
exchange of individuals across the studied beaches. However, the basic
model can be expanded to accommodate multiple state vectors,
representing several populations and multiple time series (Hinrichsen
and Holmes 2009[^3]).

[^3]: Hinrichsen R, Holmes EE. 2009. Using multivariate state-space
    models to study spatial structure and dynamics. Spatial
    Ecology.145-166.

Posterior distributions of the model parameters are numerically derived
using Markov chain Monte Carlo (MCMC) simulation in JAGS (Plummer,
2003[^4]; 2017[^5]).The MCMC simulations are based on 10,000 samples of
2 chains. Every other sample was retained to reduce auto-correlation,
and the first 1000 samples of each chain were discarded as burn-in.

[^4]: Plummer M. 2003. Jags: A program for analysis of bayesian
    graphical models using Gibbs sampling. Proceedings of the 3rd
    international workshop on distributed statistical computing. Vienna,
    Austria.

[^5]: Plummer M. 2017. Jags version 4.3.0 user manual.
    http://mcmc-jagssourceforgenet/.

From the model outputs, we are most interested in $r$, the annual
population growth rate, $Q$, the process variance, and
$\text{T}_{final}$, the estimated true log Annual Nesters for the final
year of observed data. Posterior distributions of Annual Nesters for the
final found years of data are used to estimate current abundance.

### 3. Trend analysis: future projections

PVA projections use a simulation approach with 10,000 runs for each
species. Each projection is initialized in its starting year with a
paired draw from the MCMC samples (joint posterior distribution) for (1)
Annual Nesters ($N_0$ = $\text{N}_{final}$), (2) instantaneous
population growth rate ($r$), (3) process error variance ($Q$) from the
final data year of the historic trend analysis. For each subsequent year
in the projection, a new $r$ and $Q$ are drawn as pairs from the MCMC
samples to make the projections dynamic. Pulling paired draws from the
MCMC samples reflects the inter-annual variation in the biology of the
species, but also constrains parameter values to realistic combinations
and therefore keeps the uncertainty in the projections reasonable.

Projections can be evaluated against abundance thresholds. Here, the
probability of falling below 50%, 25%, and 12.5% of current population
size ($N_0$) is calculated at 5, 10, 25, 50, and 100-year time steps by
summing the number of projections below the thresholds at the given time
step and dividing by the total number of projections (10,000). Mean,
median, and 95% confidence limits of number of years to reach the
threshold are calculated for simulations that fall below a given
population threshold, and the 100-year timestep simulation.

### 4. Incorporating fishery interactions into the model

In principle, the incorporation of fisheries interactions into the PVA
projections is simple: during the calculation of the number of females
in the next time step ($\text{N}_{j+1}$), the number of females in the
current time step ($N_j$) is reduced by the incidental take in the
current time step ($F_j$) and multiplied by the finite population growth
rate ($\lambda$, = $e^r$). $$
\text{N}_{j+1} = (N_j - F_j) * e^r
$$ Therefore, the challenge comes from converting the incidental take of
a given species (comprised of various lengths, ages, life stages, and
sexes) to adult nester equivalents (ANE).

**1. Predicting anticipated take levels:** The first goal is to generate
the number and characteristics of the anticipated turtles that will be
taken in each year. Each year's anticipated take level was drawn from a
Conway-Maxwell Poisson distribution (CMP). Each "anticipated take"
individual receives (1) a length and fishery mortality from a bivariate
normal distribution, (2) a back-calculated age with years until maturity
based on a von Bertalanffy growth model, (3) juvenile survival rate, (4)
sex, and (5) a remigration interval.

**2. Lengths and fishery mortality.** Based on historic incidental take,
a bivariate normal distribution is used to generate lengths in
logarithmic space and assign fishery mortality in logit space. The
parameters of the multivariate normal distribution are solved for in a
Bayesian framework using STAN via RStan with 7,500 simulations per chain
(5,000 burn-in, 2,500 retained) with 4 chains.

**3. Age and stage.** From all lengths of historically taken turtles, a
von Bertalanffy growth model (VBGM) is used to calculate the expected
length at age across the range of lengths for each species. Using the
VBGM for each species, the age at maturity ($A_{mat}$) was assumed to
correspond to a length of 97.5% of the maximum asymptotic maximum length
($L_\infty$). Turtles with ages less than $A_{mat}$ or lengths less than
97.5% of ($L_\infty$) are considered immature. Years until maturity are
calculated for all turtles.

**4. Remigration interval, juvenile survival, and sex.** In
deterministic runs, each individual in the anticipated take is assigned
the mean remigration interval ($RI$) and the mean juvenile survival
($\phi$). In stochastic runs, each individual's $RI$ is drawn from a
distribution (CMP for leatherbacks, truncated normal for loggerheads)
and their juvenile survival is drawn from a normal distribution. The sex
of each animal is drawn from a Bernoulli distribution for the
probability of being female.

**5. ANE calculation.** Adults in the anticipated take are given ANEs
of 1. Juvenile ANEs are calculated by projecting the juvenile survival
over the number of years to maturity, and dividing by remigration
interval. The stochastic nature of sex ratio and fishery mortality are
applied to adjust the individual ANE. The probability of an individual
taken by a fishery dying is used with a Bernoulli distribution to
simulate whether an individual dies.

**5. Historical ANE imputation.** To account for the historical impact
on the population growth rates, ANE is also calculated historically.
Each turtle's length is used to generate a likely age, stage, and years
to maturity. Juveniles' years to maturity are rounded to the nearest
year, and adults are assumed to be nesting in the year of their fishery
interaction.

**6. Take calculation.** After converting all individuals to ANEs,
"take" is used as the summation of the individual ANEs in a given year.
To account to process variance $Q$ from the trend analysis, the first
equation below is modified to draw the number of nesters in the
following year from a normal distribution. The modified population
growth model is used as the basis for the future projections described
above to produce future scenarios with take incorporated.

### 5. Conservation implications

We made a number of decisions in the analyses that were inherently
conservative for the turtle species in question (i.e., likely inflated
the mortality relative to the true). We highlight those here to provide
context for interpretation:

1.  We applied the entire anticipated take for the fishery in future
    years to the index beaches for which we had data; however, those
    index beaches represent only 52% and 75% of the nesting populations
    for loggerheads and leatherbacks, respectively. Assessing the impact
    of the entire take on the index beach populations rather than the
    full populations is conservative for the species.

2.  The Bayesian trend analysis accounts for the parameter uncertainty
    by incorporating estimated uncertainty of demographic parameters.
    Consequently, we found large uncertainty around the estimated
    population growth rate (r), which resulted in greater or lesser
    chance of recovering than what was found from a frequentist
    approach. This finding provides an accurate assessment of the
    projected population given what we know about the population.

3.  The anticipated take level is biased high (the CMP distribution
    tends to draw ATLs that are higher than the take levels observed in
    previous years).

4.  In calculating Adult Nester Equivalents (ANEs) in our historical
    analysis of fishery impacts (see Historical ANE Imputation), we
    assume that nesters would have repeatedly returned to nest at a
    constant remigration interval with an annual probability of survival
    equal to 0.89 for leatherbacks and 0.90 for loggerheads. However,
    for loggerheads, Japanese colleagues have indicated that nesters
    have a relatively low probability of being observed nesting in
    future years after their initial sighting (approximately 0.30),
    suggesting potentially high threats in the marine environment. If
    this is true, then the ANE values in our historical analysis (see
    Historical ANE Imputation) are inflated compared to the true ANE
    values (i.e., we added back loggerhead nesters to the population
    when in reality they had a low chance of surviving to the next
    nesting season).
